grails-app/domain/rc/Query.groovy
package rc

class Query {

    String queryString
    Date date = new Date()

    static constraints = {

        queryString nullable: false, blank: false
        date nullable: false
    }
}

grails-app/domain/rc/Result.groovy
package rc

class Result implements Comparable<Result>{

    @Override
    int compareTo(Result o) {
        if(this.score < o.score)
            return -1
        else
            return 1
    }

    enum Type{

        POSITIVE, NEGATIVE
    }

    String heading
    String url
    Type type
    Query query
    double score

    static constraints = {

        type nullable: false
        heading nullable: false, blank: false
        url nullable: false, blank: false
        query nullable: false
    }

    def getDomain(){

        return url.substring(0, url.lastIndexOf("/"))
    }
}

grails-app/controllers/rc/SearchController.groovy
package rc

class SearchController {

    def searchService

    def index() {

    }

    def results(){

        List<Result> positiveResults
        List<Result> negativeResults
        def keywords = params.keywords
        List<Result> results

        results = searchService.getDataFromGoogle(keywords)
        positiveResults = searchService.getPositiveResults(results)
        negativeResults = searchService.getNegativeResults(results)

        [positiveResultList: positiveResults, negativeResultList: negativeResults, query: keywords]
    }
}

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
  		<asset:stylesheet src="application.css"/>
		<asset:javascript src="application.js"/>
		<g:layoutHead/>
	</head>
	<body>
		<g:layoutBody/>
	</body>
</html>

grails-app/views/search/results.gsp
<%--
  Created by IntelliJ IDEA.
  User: asimsangram
  Date: 2/23/16
  Time: 3:36 PM
--%>

<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <title></title>

    <style>
        li{
            float: left;
        }
    </style>
</head>

<body>
    <h2>Search Query: "${query}"</h2>
    <ul style="list-style-type: none;">
        <li>
            <table border="1">
                <thead>
                    <th>S.N.</th>
                    <th>Positive Results</th>
                    <th>Score</th>
                </thead>
                <tbody>
                    <g:each in="${positiveResultList}" var="result" status="i">
                        <tr>
                            <td>
                                ${i + 1}
                            </td>
                            <td>
                                <a href="${result.url}">
                                    ${result.heading}
                                </a>
                            </td>
                            <td>
                                ${result.score}
                            </td>
                        </tr>
                    </g:each>
                </tbody>
            </table>
        </li>
        <li>
            <table border="1">
                <thead>
                    <th>S.N.</th>
                    <th>Negative Results</th>
                    <th>Score</th>
                </thead>
                <tbody>
                    <g:each in="${negativeResultList}" var="result" status="i">
                        <tr>
                            <td>
                                ${i + 1}
                            </td>
                            <td>
                                <a href="${result.url}">
                                    ${result.heading}
                                </a>
                            </td>
                            <td>
                                ${result.score}
                            </td>
                        </tr>
                    </g:each>
                </tbody>
            </table>
        </li>
    </ul>
    <div style="display: inline-block;">
        <hr>
        <g:form controller="search" action="results">
            Search Another:<input type="text" name="keywords"/>
            <input type="submit" value="Submit"/>
        </g:form>
    </div>
</body>
</html>